config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#top'
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index' ,as:'home'
  get 'todolists/:id' => 'todolists#show' ,as: 'todolist'
  get 'todolists/:id/edit' => 'todolists#edit' ,as: 'edit_todolist'
  patch 'todolists/:id' =>'todolists#update' ,as: 'update_todolist'
  delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def top
    end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
    
  def new
    @list = List.new
  end
  def index
      @lists = List.all
    @list = List.new

  end
  
  def show
      @list = List.find(params[:id])
  end
   def create
        # ストロングパラメーターを使用
         list = List.new(list_params)
        # DBへ保存する
        #  list.save
        # redirect_to todolist_path(list.id)
    if list.save
      flash[:notice] = "successfully"
      redirect_to todolist_path(list.id)
    else
      redirect_to todolist_path(list.id)
    end
    
   end
   
   def edit
       @list = List.find(params[:id])
   end
   def update
        list = List.find(params[:id])
        #list.update(list_params)
    if list.update(list_params)
      flash[:notice] = "successfully"
      redirect_to todolist_path(list.id)
    else
      redirect_to todolist_path(list.id)
    end
    
   end
   
   def destroy
        list = List.find(params[:id])
        list.destroy
        redirect_to todolists_path   
   end
  
  private
  
  def list_params
        params.require(:list).permit(:title , :body,:image)
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/home/top.html.erb
<h1>Books</h1>
<a link  href="/todolists">start</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@list, url: "/todolists/#{@list.id}") do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>    
<% end %>

app/views/todolists/index.html.erb
 <div class="books">Books</div>
  <table>
      <thead>
          <tr>
              <th>title</th>
              <th>body</th>
              <th></th>
              <th></th>
              <th></th>
          </tr>
      </thead>
      <% @lists.each do |list| %>
      <tbody>
         <tr>
         <th><%= list.title %></th>
         <th><%= list.body %></th>
         <th><%= link_to "show",todolist_path(list.id),class:"show_#{list.id}"  %></th>
         <th><%= link_to "edit", edit_todolist_path(list.id),class:"edit_#{list.id}"	%></th>
         <th><%= link_to "delete", destroy_todolist_path(list.id),method: :delete, "data-confirm" => "本当に削除しますか？",class:"delete_#{list.id}"%></th>
      </tbody>
      <% end %>
  </table>
  
  <%= form_for(@list, url: '/todolists') do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title ,class:"book_title" %>
    <h4>本文</h4>
    <%= f.text_area :body,class:"book_body" %>
    <%= f.submit '投稿' %>
    
  <% end %>
  

app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@list, url: '/todolists') do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title ,class:"book_title" %>
    <h4>本文</h4>
    <%= f.text_area :body,class:"book_body" %>
    
    <%= f.submit '投稿' %>
 
<% end %>

app/views/todolists/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>
<h2>画像</h2>
<%= attachment_image_tag @list, :image, :fill, 300, 300, format: 'jpeg' %>
<%= link_to "edit", edit_todolist_path(@list.id) ,class:"edit_#{@list_id}"%> 
<%= link_to "back", home_path(@list.id),class:"back" %> 